### ISSUE TITLE
Support more audio file formats 

### ISSUE THREAD

**Issue by juntao** [LlamaEdge/whisper-api-server#3]
We need to detect the audio file format in the request and automatically convert it to the required `wav` format before passing to whisper. Specially, we need to support the `ogg` format perhaps using the "pure Rust" ogg library below. 

https://github.com/RustAudio/audrey

Please test your implementation with these two files: 

* https://telegrambots.github.io/book/docs/voice-nfl_commentary.ogg
* https://www.dropbox.com/scl/fi/0ky7c14qz17ss7gmskent/file_0.oga?rlkey=ppqvfbgrtvhiqqodwcffzpxav&dl=0

**Comment by apepkuss** [comment]
Fixed in [0.3.3](https://github.com/LlamaEdge/whisper-api-server/releases/tag/0.3.3)
