### ISSUE TITLE
Trim silence at the end

### ISSUE THREAD

**Issue by juntao** [LlamaEdge/whisper-api-server#4]
The whisper model sometimes hallucinates at the end of the transcription if there is a silence. For example, this wav file has about 1s of silence at the end:

https://www.dropbox.com/scl/fi/b1wbo0ib8ujjjqxcu3x9q/test.wav?rlkey=gjvzvlg33jcfto5yi78byt2o0&dl=0

If you transcribe it,

```
curl --location 'https://whisper.gaia.domains/v1/audio/transcriptions' \
  --header 'Content-Type: multipart/form-data' \
  --form 'file=@"test.wav"' \
  --form 'language="en"'
```

it will generated a hallucinated transcription like the following.

```
{"text":"[00:00:00.000 --> 00:00:03.400]  This is a test record for whisper.cpp\n[00:00:03.400 --> 00:00:04.400]  I'm a little bit nervous."}

OR

{"text":"[00:00:00.000 --> 00:00:03.400]  This is a test record for whisper.cpp\n[00:00:03.400 --> 00:00:05.400]  Please subscribe to my channel if you like my video."}

OR

{"text":"[00:00:00.000 --> 00:00:03.400]  This is a test record for whisper.cpp\n[00:00:03.400 --> 00:00:15.400]  了解更多,請搜尋:IEI 威強電"}
```

But if I trim the silence at the end and get this wav file.

https://www.dropbox.com/scl/fi/py5azk37odmf92vsrotd2/test-1.wav?rlkey=6laun1qlxpgk2neuo3bskav49&dl=0

It gets the correct result every time.

```
curl --location 'https://whisper.gaia.domains/v1/audio/transcriptions' \
  --header 'Content-Type: multipart/form-data' \
  --form 'file=@"test-1.wav"' \
  --form 'language="en"'

{"text":"[00:00:00.000 --> 00:00:03.400]  This is a test record for whisper.cpp"}
```

Based on that, I think the `whsiper-api-server` should trim any silence from the end of the input audio before passing it to the AI model for inference. It should not affect the timestamp since the silence is trimmed from the end.

**Comment by apepkuss** [comment]
Fixed in [0.3.3](https://github.com/LlamaEdge/whisper-api-server/releases/tag/0.3.3)
